[package]
name = "qpl"
version = "0.1.0"
edition = "2021"
authors = [ "Quigly" ]
description = "Quigly's Platform Layer"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
