[package]
name = "qpl"
version = "0.0.1"
edition = "2021"
authors = [ "Quigly" ]
description = "Quigly's Platform Layer"
license = "MIT"
repository = "https://github.com/quigly/qpl"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
